import image.ImageCreater;
import image.ImageRenamer;

import java.awt.Component;
import java.awt.Dialog.ModalExclusionType;
import java.awt.SystemColor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.util.Date;
import java.util.Timer;

import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import common.DigitDocument;
import common.DirectoriesFilter;
import common.ExcelFilter;
import common.FileUtil;
import common.FontUtil;
import common.StateTimerTask;

import excel.ExcelParser;
import global.Global;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * 
 * @author AngryPotato
 */
@SuppressWarnings("serial")
public class PieceImageView extends javax.swing.JFrame {

	/**
	 * Excel解析器
	 * */
	private ExcelParser excelParser;

	/**
	 * 主线程计时器，每0.5秒检测运行状态一次
	 * */
	private Timer timer;

	/**
	 * Creates new form PieceImage
	 */
	public PieceImageView() {
		setForeground(SystemColor.inactiveCaptionBorder);
		setFont(FontUtil.default_font);
		setResizable(false);
		setModalExclusionType(ModalExclusionType.TOOLKIT_EXCLUDE);
		getContentPane().setBackground(SystemColor.inactiveCaptionBorder);
		setBackground(SystemColor.inactiveCaptionBorder);

		initComponents();

		changeStateByRadio();
		// 设置默认值
		gTxtQua.setText("30");
		gTxtW.setText("150");
		gTxtH.setText("200");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel1.setFont(FontUtil.default_font);
		jLabel1.setBackground(SystemColor.inactiveCaptionBorder);
		gTxtExcel = new javax.swing.JTextField();
		gTxtExcel.setFont(FontUtil.default_font);
		gBtnExcel = new javax.swing.JButton();
		gBtnExcel.setSize(65, 25);
		gBtnExcel.setFont(FontUtil.default_font);
		gBtnExcel.setBackground(SystemColor.inactiveCaptionBorder);
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setFont(FontUtil.default_font);
		jLabel2.setBackground(SystemColor.inactiveCaptionBorder);
		gTxtSrcImage = new javax.swing.JTextField();
		gTxtSrcImage.setFont(FontUtil.default_font);
		gTxtSrcImage.setColumns(10);
		gBtnSrcImage = new javax.swing.JButton();
		gBtnSrcImage.setSize(65, 25);
		gBtnSrcImage.setFont(FontUtil.default_font);
		gBtnSrcImage.setBackground(SystemColor.inactiveCaptionBorder);
		jLabel3 = new javax.swing.JLabel();
		jLabel3.setFont(FontUtil.default_font);
		jLabel3.setBackground(SystemColor.inactiveCaptionBorder);
		gTxtState = new javax.swing.JTextField();
		gTxtState.setFont(FontUtil.default_font);
		gTxtState.setBackground(SystemColor.inactiveCaptionBorder);
		gStateBar = new javax.swing.JProgressBar();
		gStateBar.setBackground(SystemColor.inactiveCaptionBorder);
		gBtnPiece = new javax.swing.JButton();
		gBtnPiece.setFont(FontUtil.default_font);
		gBtnPiece.setBackground(SystemColor.inactiveCaptionBorder);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("照片合成 v1.1");
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		setIconImages(null);
		setName(""); // NOI18N

		jLabel1.setText("照片信息excel");

		gTxtExcel.setBackground(SystemColor.inactiveCaptionBorder);
		gTxtExcel
				.setText("C:\\Users\\AngryPotato\\Desktop\\长安大学（贵阳公路学校办学点）2013年5月9日照未过成高10人\\1.xlsx");
		gTxtExcel.setToolTipText("");

		gBtnExcel.setText("选择...");
		gBtnExcel.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				onBtnExcelMouseClicked(e);
			}
		});

		jLabel2.setText("原始照片目录");

		gTxtSrcImage.setBackground(SystemColor.inactiveCaptionBorder);
		gTxtSrcImage
				.setText("C:\\Users\\AngryPotato\\Desktop\\长安大学（贵阳公路学校办学点）2013年5月9日照未过成高10人\\1\\");

		gBtnSrcImage.setText("选择...");
		gBtnSrcImage.addActionListener(
				new ActionListener() {
					
					@Override
					public void actionPerformed(ActionEvent e) {
						onBtnSrcImageMouseClicked(e);
					}
				}
		);

		jLabel3.setText("当前状态");

		gTxtState.setText("未开始...");
		gTxtState.setEnabled(false);

		gBtnPiece.setText("合成");
		gBtnPiece.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				onBtnPieceMouseClicked(e);
			}
		});

		gRadioPiece = new JRadioButton("合成照片");
		gRadioPiece.setSelected(true);
		gRadioPiece.addChangeListener(new ChangeListener() {
			@Override
			public void stateChanged(ChangeEvent arg0) {
				changeStateByRadio();
			}
		});
		gRadioPiece.setFont(FontUtil.default_font);
		menuGroup.add(gRadioPiece);

		JRadioButton gRadioRename = new JRadioButton("原始照片重命名");
		gRadioRename.setSelected(true);
		gRadioRename.setFont(FontUtil.default_font);
		menuGroup.add(gRadioRename);

		panel = new JPanel();
		panel.setBackground(SystemColor.inactiveCaptionBorder);

		gTxtQua = new JTextField();
		gTxtQua.setFont(FontUtil.default_font);
		gTxtQua.setColumns(10);
		gTxtQua.setDocument(new DigitDocument(3));
		gTxtQua.addKeyListener(new KeyListener() {

			@Override
			public void keyTyped(KeyEvent arg0) {
				if (gTxtQua.getText().trim().length() == 2
						&& Character.isDigit(arg0.getKeyChar())) {
					gTxtQua.setText("100");
				}
			}

			@Override
			public void keyReleased(KeyEvent arg0) {
				// TODO Auto-generated method stub

			}

			@Override
			public void keyPressed(KeyEvent arg0) {
			}
		});

		JLabel label = new JLabel("图片质量");

		JLabel label_1 = new JLabel("%");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(6)
					.addComponent(gRadioPiece)
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addComponent(gRadioRename)
					.addContainerGap(508, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup()
					.addGap(54)
					.addComponent(gStateBar, GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
					.addGap(48))
				.addGroup(layout.createSequentialGroup()
					.addGap(191)
					.addComponent(label)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(gTxtQua, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(label_1, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
					.addGap(107)
					.addComponent(gBtnPiece)
					.addContainerGap(227, Short.MAX_VALUE))
				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
					.addContainerGap(121, Short.MAX_VALUE)
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addComponent(panel, GroupLayout.PREFERRED_SIZE, 547, GroupLayout.PREFERRED_SIZE)
							.addContainerGap())
						.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel3)
								.addGroup(layout.createSequentialGroup()
									.addPreferredGap(ComponentPlacement.RELATED)
									.addComponent(jLabel2))
								.addGroup(layout.createSequentialGroup()
									.addPreferredGap(ComponentPlacement.RELATED)
									.addComponent(jLabel1)))
							.addGap(4)
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addComponent(gTxtSrcImage, GroupLayout.PREFERRED_SIZE, 349, GroupLayout.PREFERRED_SIZE)
								.addComponent(gTxtExcel, GroupLayout.PREFERRED_SIZE, 349, GroupLayout.PREFERRED_SIZE)
								.addComponent(gTxtState, GroupLayout.PREFERRED_SIZE, 342, GroupLayout.PREFERRED_SIZE))
							.addGap(30)
							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(gBtnExcel)
								.addComponent(gBtnSrcImage))
							.addGap(48))))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap(6, Short.MAX_VALUE)
					.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
						.addGroup(layout.createSequentialGroup()
							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(gRadioPiece)
								.addComponent(gRadioRename))
							.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
									.addGap(17)
									.addComponent(gBtnExcel))
								.addGroup(layout.createSequentialGroup()
									.addGap(21)
									.addComponent(jLabel1))))
						.addGroup(layout.createSequentialGroup()
							.addComponent(gTxtExcel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
							.addGap(1)))
					.addPreferredGap(ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
					.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
						.addGroup(layout.createSequentialGroup()
							.addComponent(gBtnSrcImage)
							.addPreferredGap(ComponentPlacement.UNRELATED))
						.addGroup(layout.createSequentialGroup()
							.addComponent(jLabel2)
							.addGap(14))
						.addGroup(layout.createSequentialGroup()
							.addComponent(gTxtSrcImage, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
							.addGap(11)))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(panel, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel3)
						.addComponent(gTxtState, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))
					.addGap(18)
					.addComponent(gStateBar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(gBtnPiece)
						.addComponent(gTxtQua, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(label)
						.addComponent(label_1))
					.addContainerGap(17, Short.MAX_VALUE))
		);
		layout.linkSize(SwingConstants.HORIZONTAL, new Component[] {gTxtExcel, gTxtSrcImage});
		layout.linkSize(SwingConstants.HORIZONTAL, new Component[] {jLabel1, jLabel2});
		layout.linkSize(SwingConstants.HORIZONTAL, new Component[] {gBtnExcel, gBtnSrcImage});
		panel.setLayout(null);

		JPanel panel_1 = new JPanel();
		panel_1.setBackground(SystemColor.inactiveCaptionBorder);
		panel_1.setBounds(-70, 0, 632, 41);
		panel.add(panel_1);
		panel_1.setLayout(null);

		gLabelW = new JLabel("宽度");
		gLabelW.setFont(FontUtil.default_font);
		gLabelW.setBounds(156, 15, 54, 15);
		panel_1.add(gLabelW);

		gTxtW = new JTextField();
		gTxtW.setFont(FontUtil.default_font);
		gTxtW.setBounds(185, 12, 66, 21);
		panel_1.add(gTxtW);
		gTxtW.setColumns(10);
		gTxtW.setDocument(new DigitDocument(4));

		gLabelWUnit = new JLabel("px");
		gLabelWUnit.setFont(FontUtil.default_font);
		gLabelWUnit.setBounds(251, 15, 54, 15);
		panel_1.add(gLabelWUnit);

		gLabelH = new JLabel("高度");
		gLabelH.setFont(FontUtil.default_font);
		gLabelH.setBounds(351, 15, 54, 15);
		panel_1.add(gLabelH);

		gTxtH = new JTextField();
		gTxtH.setFont(FontUtil.default_font);
		gTxtH.setBounds(379, 12, 66, 21);
		panel_1.add(gTxtH);
		gTxtH.setColumns(10);
		gTxtH.setDocument(new DigitDocument(4));

		gLabelHUnit = new JLabel("px");
		gLabelHUnit.setFont(FontUtil.default_font);
		gLabelHUnit.setBounds(446, 15, 54, 15);
		panel_1.add(gLabelHUnit);

		gTxtTarget = new JTextField();
		gTxtTarget.setBounds(150, 11, 350, 23);
		panel_1.add(gTxtTarget);
		gTxtTarget
				.setText("C:\\Users\\AngryPotato\\Desktop\\长安大学（贵阳公路学校办学点）2013年5月9日照未过成高10人\\1_new\\");
		gTxtTarget.setFont(FontUtil.default_font);
		gTxtTarget.setColumns(10);
		gTxtTarget.setBackground(SystemColor.inactiveCaptionBorder);
		layout.setAutoCreateContainerGaps(true);
		layout.setAutoCreateGaps(true);
		getContentPane().setLayout(layout);

		pack();

		Global.txtExcel = gTxtExcel;
		Global.txtSrcImage = gTxtSrcImage;
		Global.btnExcel = gBtnExcel;
		Global.btnSrcImage = gBtnSrcImage;
		Global.btnPiece = gBtnPiece;
		Global.txtTarget = gTxtTarget;
		Global.txtState = gTxtState;
		Global.stateBar = gStateBar;
		Global.radioPiece = gRadioPiece;
		Global.radioRename = gRadioRename;
		Global.txtW = gTxtW;
		Global.txtH = gTxtH;
		
				gLabelTarget = new JLabel("生成图片目录");
				gLabelTarget.setBounds(70, 14, 72, 17);
				panel_1.add(gLabelTarget);
				gLabelTarget.setFont(FontUtil.default_font);
				gLabelTarget.setBackground(SystemColor.inactiveCaptionBorder);
				
						gBtnTarget = new JButton("选择...");
						gBtnTarget.setBounds(530, 10, 65, 25);
						panel_1.add(gBtnTarget);
						gBtnTarget.setFont(FontUtil.default_font);
						gBtnTarget.setBackground(SystemColor.inactiveCaptionBorder);
						Global.btnTarget = gBtnTarget;
		Global.txtQua = gTxtQua;
	}// </editor-fold>//GEN-END:initComponents

	private void changeStateByRadio() {
		gLabelTarget.setVisible(gRadioPiece.isSelected());
		gTxtTarget.setVisible(gRadioPiece.isSelected());
		gBtnTarget.setVisible(gRadioPiece.isSelected());
		gLabelW.setVisible(!gRadioPiece.isSelected());
		gTxtW.setVisible(!gRadioPiece.isSelected());
		gLabelWUnit.setVisible(!gRadioPiece.isSelected());
		gLabelH.setVisible(!gRadioPiece.isSelected());
		gTxtH.setVisible(!gRadioPiece.isSelected());
		gLabelHUnit.setVisible(!gRadioPiece.isSelected());
	}

	/**
	 * 选择excel配置文件按钮被点击
	 * 
	 */
	private void onBtnExcelMouseClicked(ActionEvent e) {// GEN-FIRST:event_onBtnExcelMouseClicked
		// TODO add your handling code here:
		JFileChooser chooser = new JFileChooser();
		chooser.setFileFilter(new ExcelFilter());
		chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
		chooser.setAcceptAllFileFilterUsed(false);
		chooser.setDialogTitle("选择excel信息文件:");
		chooser.showOpenDialog(null);
		File file = chooser.getSelectedFile();
		if (file != null && file.exists() && file.isFile()) {
			gTxtExcel.setText(chooser.getSelectedFile().getAbsolutePath());
		}
	}// GEN-LAST:event_onBtnExcelMouseClicked

	/**
	 * 原始照片路径按钮被点击
	 * 
	 */
	private void onBtnSrcImageMouseClicked(ActionEvent e) {// GEN-FIRST:event_onBtnSaveMouseClicked
		// TODO add your handling code here:
		JFileChooser chooser = new JFileChooser();
		chooser.setFileFilter(new DirectoriesFilter());
		chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		chooser.setAcceptAllFileFilterUsed(false);
		chooser.setDialogTitle("原始照片路径:");
		chooser.showOpenDialog(null);
		File file = chooser.getSelectedFile();
		if (file != null && file.exists()) {
			gTxtSrcImage.setText(chooser.getSelectedFile().getAbsolutePath());
		}
	}// GEN-LAST:event_onBtnSaveMouseClicked

	/**
	 * 合成按钮被点击
	 * 
	 */
	private void onBtnPieceMouseClicked(ActionEvent evt) {// GEN-FIRST:event_onBtnPieceMouseClicked
		// TODO add your handling code here:
		Global.setEnable(false);
		if (checkURL() == false) {
			Global.setEnable(true);
			return;
		}
		Global.setState(Global.STATE_LOAD_EXCEL);
		Global.startTime = new Date();
		if (excelParser == null) {
			excelParser = new ExcelParser();
		}
		excelParser.init();
		try {
			excelParser.readExcel(gTxtExcel.getText());
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			Global.setEnable(true);
			JOptionPane.showMessageDialog(null, "解析excel失败!");
			return;
		}
		if (gRadioPiece.isSelected()) {
			ImageCreater.startThread();
		} else {
			ImageRenamer.startThread();
		}
		timer = new Timer();
		timer.schedule(new StateTimerTask(), 1000, 500);
	}// GEN-LAST:event_onBtnPieceMouseClicked

	/**
	 * 检测URL是否有问题
	 * 
	 */
	private boolean checkURL() {
		if (common.FileUtil.checkIsExcel(gTxtExcel.getText()) == false) {
			JOptionPane.showMessageDialog(null, "照片excel信息路径错误");
			return false;
		}
		if (FileUtil.checkIsDir(gTxtSrcImage.getText()) == false) {
			JOptionPane.showMessageDialog(null, "原始照片路径错误");
			return false;
		}
		if (FileUtil.checkIsDir(gTxtTarget.getText()) == false) {
			JOptionPane.showMessageDialog(null, "合成后存放图片目录错误");
			return false;
		}
		Global.srcImageURL = gTxtSrcImage.getText();
		Global.targetImageURL = gTxtTarget.getText();
		return true;
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PieceImageView.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PieceImageView.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PieceImageView.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PieceImageView.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				PieceImageView frame = new PieceImageView();
				frame.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton gBtnExcel;
	private javax.swing.JButton gBtnPiece;
	private javax.swing.JButton gBtnSrcImage;
	private javax.swing.JTextField gTxtExcel;
	private javax.swing.JTextField gTxtSrcImage;
	private javax.swing.JTextField gTxtState;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JProgressBar gStateBar;
	private final ButtonGroup menuGroup = new ButtonGroup();
	private JRadioButton gRadioPiece;
	private JPanel panel;
	private JLabel gLabelTarget;
	private JButton gBtnTarget;
	private JLabel gLabelW;
	private JTextField gTxtW;
	private JLabel gLabelWUnit;
	private JLabel gLabelH;
	private JTextField gTxtH;
	private JLabel gLabelHUnit;
	private JTextField gTxtTarget;
	private JTextField gTxtQua;
}
