import image.ImageCreater;

import java.io.File;
import java.util.Date;
import java.util.Timer;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import timer.StateTimerTask;
import excel.ExcelParser;
import fileUtil.DirectoriesFilter;
import fileUtil.ExcelFilter;
import fileUtil.FileUtil;
import global.Global;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * 
 * @author AngryPotato
 */
@SuppressWarnings("serial")
public class PieceImage extends javax.swing.JFrame {

	/**
	 * Excel解析器
	 * */
	private ExcelParser excelParser;

	/**
	 * 主线程计时器，每0.5秒检测运行状态一次
	 * */
	private Timer timer;

	/**
	 * Creates new form PieceImage
	 */
	public PieceImage() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		gTxtExcel = new javax.swing.JTextField();
		gBtnExcel = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		gTxtSrcImage = new javax.swing.JTextField();
		gBtnSrcImage = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		gTxtState = new javax.swing.JTextField();
		gStateBar = new javax.swing.JProgressBar();
		gBtnPiece = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("照片合成 v1.0 beta");
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		setIconImages(null);
		setName(""); // NOI18N

		jLabel1.setText("照片信息excel");

		gTxtExcel.setBackground(new java.awt.Color(204, 204, 204));
		gTxtExcel.setText("C:\\Users\\AngryPotato\\Desktop\\高校18人\\高校18人\\原图\\4.24-18.xls");
		gTxtExcel.setToolTipText("");

		gBtnExcel.setText("选择...");
		gBtnExcel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				onBtnExcelMouseClicked(evt);
			}
		});

		jLabel2.setText("原始照片目录");

		gTxtSrcImage.setBackground(new java.awt.Color(204, 204, 204));
		gTxtSrcImage.setText("C:\\Users\\AngryPotato\\Desktop\\高校18人\\高校18人\\原图");

		gBtnSrcImage.setText("选择...");
		gBtnSrcImage.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				onBtnSrcImageMouseClicked(evt);
			}
		});

		jLabel3.setText("当前状态");

		gTxtState.setText("未开始...");
		gTxtState.setEnabled(false);

		gBtnPiece.setText("合成");
		gBtnPiece.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				onBtnPieceMouseClicked(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addGap(254, 254, 254)
								.addComponent(gBtnPiece)
								.addContainerGap(259, Short.MAX_VALUE))
				.addGroup(
						layout.createSequentialGroup()
								.addGap(30, 30, 30)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel3)
																.addContainerGap(
																		492,
																		Short.MAX_VALUE))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						gStateBar,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						510,
																						Short.MAX_VALUE)
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.LEADING,
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addComponent(
																																		jLabel2)
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																.addComponent(
																																		gTxtSrcImage,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		335,
																																		Short.MAX_VALUE))
																												.addGroup(
																														layout.createSequentialGroup()
																																.addComponent(
																																		jLabel1)
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																.addComponent(
																																		gTxtExcel,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		329,
																																		Short.MAX_VALUE)))
																								.addGap(18,
																										18,
																										18)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														gBtnExcel)
																												.addComponent(
																														gBtnSrcImage)))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(0,
																										74,
																										Short.MAX_VALUE)
																								.addComponent(
																										gTxtState,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										436,
																										javax.swing.GroupLayout.PREFERRED_SIZE)))
																.addGap(30, 30,
																		30)))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(37, 37, 37)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														gTxtExcel,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(gBtnExcel))
								.addGap(28, 28, 28)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														gTxtSrcImage,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(gBtnSrcImage))
								.addGap(38, 38, 38)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(
														gTxtState,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addComponent(gStateBar,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(gBtnPiece)
								.addContainerGap(18, Short.MAX_VALUE)));

		pack();

		Global.txtExcel = gTxtExcel;
		Global.txtSrcImage = gTxtSrcImage;
		Global.btnExcel = gBtnExcel;
		Global.btnSrcImage = gBtnSrcImage;
		Global.btnPiece = gBtnPiece;
		Global.txtState = gTxtState;
		Global.stateBar = gStateBar;
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * 选择excel配置文件按钮被点击
	 * 
	 */
	private void onBtnExcelMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_onBtnExcelMouseClicked
		// TODO add your handling code here:
		JFileChooser chooser = new JFileChooser();
		chooser.setFileFilter(new ExcelFilter());
		chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
		chooser.setAcceptAllFileFilterUsed(false);
		chooser.setDialogTitle("选择excel信息文件:");
		chooser.showOpenDialog(null);
		File file = chooser.getSelectedFile();
		if (file != null && file.exists() && file.isFile()) {
			gTxtExcel.setText(chooser.getSelectedFile().getAbsolutePath());
		}
	}// GEN-LAST:event_onBtnExcelMouseClicked

	/**
	 * 原始照片路径按钮被点击
	 * 
	 */
	private void onBtnSrcImageMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_onBtnSaveMouseClicked
		// TODO add your handling code here:
		JFileChooser chooser = new JFileChooser();
		chooser.setFileFilter(new DirectoriesFilter());
		chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		chooser.setAcceptAllFileFilterUsed(false);
		chooser.setDialogTitle("原始照片路径:");
		chooser.showOpenDialog(null);
		File file = chooser.getSelectedFile();
		if (file != null && file.exists()) {
			gTxtSrcImage.setText(chooser.getSelectedFile().getAbsolutePath());
		}
	}// GEN-LAST:event_onBtnSaveMouseClicked

	/**
	 * 合成按钮被点击
	 * 
	 */
	private void onBtnPieceMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_onBtnPieceMouseClicked
		// TODO add your handling code here:
		if (checkURL() == false) {
			return;
		}
		Global.startTime = new Date();
		Global.setEnable(false);
		Global.setState(Global.STATE_LOAD_EXCEL);
		if (excelParser == null) {
			excelParser = new ExcelParser();
		}
		excelParser.init();
		try {
			excelParser.readExcel(gTxtExcel.getText());
		} catch (Exception e) {
			// TODO Auto-generated catch block
			JOptionPane.showMessageDialog(null, "解析excel失败!");
			Global.setEnable(true);
			e.printStackTrace();
			return;
		}
		ImageCreater.startThread();
		timer = new Timer();
		timer.schedule(new StateTimerTask(), 1000, 500);

	}// GEN-LAST:event_onBtnPieceMouseClicked

	/**
	 * 检测URL是否有问题
	 * 
	 */
	private boolean checkURL() {
		if (fileUtil.FileUtil.checkIsExcel(gTxtExcel.getText()) == false) {
			JOptionPane.showMessageDialog(null, "照片excel信息路径错误");
			return false;
		}
		if (FileUtil.checkIsDir(gTxtSrcImage.getText()) == false) {
			JOptionPane.showMessageDialog(null, "原始照片路径错误");
			return false;
		}
		Global.srcImageURL = gTxtSrcImage.getText();
		return true;
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PieceImage.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PieceImage.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PieceImage.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PieceImage.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PieceImage().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton gBtnExcel;
	private javax.swing.JButton gBtnPiece;
	private javax.swing.JButton gBtnSrcImage;
	private javax.swing.JTextField gTxtExcel;
	private javax.swing.JTextField gTxtSrcImage;
	private javax.swing.JTextField gTxtState;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JProgressBar gStateBar;
	// End of variables declaration//GEN-END:variables
}
