import image.ImageCreater;
import image.ImageRenamer;

import java.awt.Component;
import java.awt.Dialog.ModalExclusionType;
import java.awt.Font;
import java.awt.SystemColor;
import java.io.File;
import java.util.Date;
import java.util.Timer;

import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import timer.StateTimerTask;
import excel.ExcelParser;
import fileUtil.DirectoriesFilter;
import fileUtil.ExcelFilter;
import fileUtil.FileUtil;
import global.Global;
import java.awt.Window.Type;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * 
 * @author AngryPotato
 */
@SuppressWarnings("serial")
public class PieceImage extends javax.swing.JFrame {

	/**
	 * Excel解析器
	 * */
	private ExcelParser excelParser;

	/**
	 * 主线程计时器，每0.5秒检测运行状态一次
	 * */
	private Timer timer;

	/**
	 * Creates new form PieceImage
	 */
	public PieceImage() {
		setForeground(SystemColor.inactiveCaptionBorder);
		setFont(new Font("Microsoft YaHei UI", Font.PLAIN, 12));
		setType(Type.UTILITY);
		setResizable(false);
		setModalExclusionType(ModalExclusionType.TOOLKIT_EXCLUDE);
		getContentPane().setBackground(SystemColor.inactiveCaptionBorder);
		setBackground(SystemColor.inactiveCaptionBorder);

		initComponents();

		changeStateByRadio();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel1.setFont(new Font("Microsoft YaHei", Font.PLAIN, 12));
		jLabel1.setBackground(SystemColor.inactiveCaptionBorder);
		gTxtExcel = new javax.swing.JTextField();
		gTxtExcel.setFont(new Font("Microsoft YaHei", Font.PLAIN, 12));
		gBtnExcel = new javax.swing.JButton();
		gBtnExcel.setFont(new Font("Microsoft YaHei", Font.PLAIN, 12));
		gBtnExcel.setBackground(SystemColor.inactiveCaptionBorder);
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setFont(new Font("Microsoft YaHei", Font.PLAIN, 12));
		jLabel2.setBackground(SystemColor.inactiveCaptionBorder);
		gTxtSrcImage = new javax.swing.JTextField();
		gTxtSrcImage.setFont(new Font("Microsoft YaHei", Font.PLAIN, 12));
		gTxtSrcImage.setColumns(10);
		gBtnSrcImage = new javax.swing.JButton();
		gBtnSrcImage.setFont(new Font("Microsoft YaHei", Font.PLAIN, 12));
		gBtnSrcImage.setBackground(SystemColor.inactiveCaptionBorder);
		jLabel3 = new javax.swing.JLabel();
		jLabel3.setFont(new Font("Microsoft YaHei", Font.PLAIN, 12));
		jLabel3.setBackground(SystemColor.inactiveCaptionBorder);
		gTxtState = new javax.swing.JTextField();
		gTxtState.setFont(new Font("Microsoft YaHei", Font.PLAIN, 12));
		gTxtState.setBackground(SystemColor.inactiveCaptionBorder);
		gStateBar = new javax.swing.JProgressBar();
		gStateBar.setBackground(SystemColor.inactiveCaptionBorder);
		gBtnPiece = new javax.swing.JButton();
		gBtnPiece.setFont(new Font("Microsoft YaHei", Font.PLAIN, 12));
		gBtnPiece.setBackground(SystemColor.inactiveCaptionBorder);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("照片合成 v1.0 beta");
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		setIconImages(null);
		setName(""); // NOI18N

		jLabel1.setText("照片信息excel");

		gTxtExcel.setBackground(SystemColor.inactiveCaptionBorder);
		gTxtExcel
				.setText("C:\\Users\\AngryPotato\\Desktop\\长安大学（贵阳公路学校办学点）2013年5月9日照未过成高10人\\1.xlsx");
		gTxtExcel.setToolTipText("");

		gBtnExcel.setText("选择...");
		gBtnExcel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				onBtnExcelMouseClicked(evt);
			}
		});

		jLabel2.setText("原始照片目录");

		gTxtSrcImage.setBackground(SystemColor.inactiveCaptionBorder);
		gTxtSrcImage
				.setText("C:\\Users\\AngryPotato\\Desktop\\长安大学（贵阳公路学校办学点）2013年5月9日照未过成高10人\\1\\");

		gBtnSrcImage.setText("选择...");
		gBtnSrcImage.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				onBtnSrcImageMouseClicked(evt);
			}
		});

		jLabel3.setText("当前状态");

		gTxtState.setText("未开始...");
		gTxtState.setEnabled(false);

		gBtnPiece.setText("合成");
		gBtnPiece.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				onBtnPieceMouseClicked(evt);
			}
		});

		gRadioPiece = new JRadioButton("合成照片");
		gRadioPiece.setSelected(true);
		gRadioPiece.addChangeListener(new ChangeListener() {
			public void stateChanged(ChangeEvent arg0) {
				changeStateByRadio();
			}
		});
		gRadioPiece.setFont(new Font("Microsoft YaHei", Font.PLAIN, 12));
		menuGroup.add(gRadioPiece);

		JRadioButton gRadioRename = new JRadioButton("原始照片重命名");
		gRadioRename.setSelected(true);
		gRadioRename.setFont(new Font("Microsoft YaHei", Font.PLAIN, 12));
		menuGroup.add(gRadioRename);

		panel = new JPanel();
		panel.setBackground(SystemColor.inactiveCaptionBorder);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(layout
				.createParallelGroup(Alignment.TRAILING)
				.addGroup(
						layout.createSequentialGroup().addGap(6)
								.addComponent(gRadioPiece)
								.addPreferredGap(ComponentPlacement.UNRELATED)
								.addComponent(gRadioRename)
								.addContainerGap(454, Short.MAX_VALUE))
				.addGroup(
						layout.createSequentialGroup()
								.addGap(54)
								.addComponent(gStateBar,
										GroupLayout.DEFAULT_SIZE, 542,
										Short.MAX_VALUE).addGap(48))
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap(71, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												Alignment.TRAILING, false)
												.addComponent(panel,
														Alignment.LEADING, 0,
														0, Short.MAX_VALUE)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				Alignment.LEADING)
																				.addComponent(
																						jLabel3)
																				.addComponent(
																						jLabel2)
																				.addComponent(
																						jLabel1))
																.addPreferredGap(
																		ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				Alignment.LEADING,
																				false)
																				.addComponent(
																						gTxtState,
																						GroupLayout.PREFERRED_SIZE,
																						GroupLayout.DEFAULT_SIZE,
																						GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						gTxtSrcImage,
																						GroupLayout.PREFERRED_SIZE,
																						349,
																						GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						gTxtExcel,
																						GroupLayout.PREFERRED_SIZE,
																						349,
																						GroupLayout.PREFERRED_SIZE))
																.addGap(30)
																.addGroup(
																		layout.createParallelGroup(
																				Alignment.TRAILING)
																				.addComponent(
																						gBtnExcel)
																				.addComponent(
																						gBtnSrcImage))))
								.addGap(48))
				.addGroup(
						Alignment.LEADING,
						layout.createSequentialGroup().addGap(288)
								.addComponent(gBtnPiece)
								.addContainerGap(299, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												Alignment.BASELINE)
												.addComponent(gRadioPiece)
												.addComponent(gRadioRename))
								.addGap(17)
								.addGroup(
										layout.createParallelGroup(
												Alignment.TRAILING)
												.addGroup(
														layout.createParallelGroup(
																Alignment.BASELINE)
																.addComponent(
																		gTxtExcel,
																		GroupLayout.PREFERRED_SIZE,
																		GroupLayout.DEFAULT_SIZE,
																		GroupLayout.PREFERRED_SIZE)
																.addComponent(
																		jLabel1))
												.addComponent(gBtnExcel))
								.addGap(18)
								.addGroup(
										layout.createParallelGroup(
												Alignment.LEADING)
												.addComponent(jLabel2,
														Alignment.TRAILING)
												.addComponent(
														gTxtSrcImage,
														Alignment.TRAILING,
														GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE,
														GroupLayout.PREFERRED_SIZE)
												.addComponent(gBtnSrcImage,
														Alignment.TRAILING))
								.addPreferredGap(ComponentPlacement.UNRELATED)
								.addComponent(panel,
										GroupLayout.PREFERRED_SIZE, 41,
										GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(
														gTxtState,
														GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE,
														GroupLayout.PREFERRED_SIZE))
								.addGap(18)
								.addComponent(gStateBar,
										GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.UNRELATED)
								.addComponent(gBtnPiece)
								.addContainerGap(17, Short.MAX_VALUE)));
		layout.linkSize(SwingConstants.HORIZONTAL, new Component[] { gBtnExcel,
				gBtnSrcImage });
		layout.linkSize(SwingConstants.HORIZONTAL, new Component[] { jLabel1,
				jLabel2 });
		layout.linkSize(SwingConstants.HORIZONTAL, new Component[] { gTxtExcel,
				gTxtSrcImage, gTxtState });

		gLabelTarget = new JLabel("生成图片目录");
		gLabelTarget.setBounds(0, 11, 72, 17);
		gLabelTarget.setFont(new Font("Microsoft YaHei", Font.PLAIN, 12));
		gLabelTarget.setBackground(SystemColor.inactiveCaptionBorder);

		gBtnTarget = new JButton("选择...");
		gBtnTarget.setBounds(460, 7, 65, 25);
		gBtnTarget.setFont(new Font("Microsoft YaHei", Font.PLAIN, 12));
		gBtnTarget.setBackground(SystemColor.inactiveCaptionBorder);
		panel.setLayout(null);
		panel.add(gLabelTarget);
		panel.add(gBtnTarget);

		JPanel panel_1 = new JPanel();
		panel_1.setBackground(SystemColor.inactiveCaptionBorder);
		panel_1.setBounds(-70, 0, 643, 41);
		panel.add(panel_1);
		panel_1.setLayout(null);

		gLabelW = new JLabel("宽度");
		gLabelW.setFont(new Font("Microsoft YaHei UI", Font.PLAIN, 12));
		gLabelW.setBounds(156, 15, 54, 15);
		panel_1.add(gLabelW);

		gTxtW = new JTextField();
		gTxtW.setFont(new Font("Microsoft YaHei UI", Font.PLAIN, 12));
		gTxtW.setBounds(185, 12, 66, 21);
		panel_1.add(gTxtW);
		gTxtW.setColumns(10);

		gLabelWUnit = new JLabel("px");
		gLabelWUnit.setFont(new Font("Microsoft YaHei UI", Font.PLAIN, 12));
		gLabelWUnit.setBounds(251, 15, 54, 15);
		panel_1.add(gLabelWUnit);

		gLabelH = new JLabel("高度");
		gLabelH.setFont(new Font("Microsoft YaHei UI", Font.PLAIN, 12));
		gLabelH.setBounds(351, 15, 54, 15);
		panel_1.add(gLabelH);

		gTxtH = new JTextField();
		gTxtH.setFont(new Font("Microsoft YaHei UI", Font.PLAIN, 12));
		gTxtH.setBounds(379, 12, 66, 21);
		panel_1.add(gTxtH);
		gTxtH.setColumns(10);

		gLabelHUnit = new JLabel("px");
		gLabelHUnit.setFont(new Font("Microsoft YaHei UI", Font.PLAIN, 12));
		gLabelHUnit.setBounds(446, 15, 54, 15);
		panel_1.add(gLabelHUnit);

		gTxtTarget = new JTextField();
		gTxtTarget.setBounds(150, 12, 350, 23);
		panel_1.add(gTxtTarget);
		gTxtTarget
				.setText("C:\\Users\\AngryPotato\\Desktop\\长安大学（贵阳公路学校办学点）2013年5月9日照未过成高10人\\1_new\\");
		gTxtTarget.setFont(new Font("Microsoft YaHei", Font.PLAIN, 12));
		gTxtTarget.setColumns(10);
		gTxtTarget.setBackground(SystemColor.inactiveCaptionBorder);
		layout.setAutoCreateContainerGaps(true);
		layout.setAutoCreateGaps(true);
		getContentPane().setLayout(layout);

		pack();

		Global.txtExcel = gTxtExcel;
		Global.txtSrcImage = gTxtSrcImage;
		Global.btnExcel = gBtnExcel;
		Global.btnSrcImage = gBtnSrcImage;
		Global.btnPiece = gBtnPiece;
		Global.txtState = gTxtState;
		Global.stateBar = gStateBar;
	}// </editor-fold>//GEN-END:initComponents

	private void changeStateByRadio() {
		gLabelTarget.setVisible(gRadioPiece.isSelected());
		gTxtTarget.setVisible(gRadioPiece.isSelected());
		gBtnTarget.setVisible(gRadioPiece.isSelected());
		gLabelW.setVisible(!gRadioPiece.isSelected());
		gTxtW.setVisible(!gRadioPiece.isSelected());
		gLabelWUnit.setVisible(!gRadioPiece.isSelected());
		gLabelH.setVisible(!gRadioPiece.isSelected());
		gTxtH.setVisible(!gRadioPiece.isSelected());
		gLabelHUnit.setVisible(!gRadioPiece.isSelected());

	}

	/**
	 * 选择excel配置文件按钮被点击
	 * 
	 */
	private void onBtnExcelMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_onBtnExcelMouseClicked
		// TODO add your handling code here:
		JFileChooser chooser = new JFileChooser();
		chooser.setFileFilter(new ExcelFilter());
		chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
		chooser.setAcceptAllFileFilterUsed(false);
		chooser.setDialogTitle("选择excel信息文件:");
		chooser.showOpenDialog(null);
		File file = chooser.getSelectedFile();
		if (file != null && file.exists() && file.isFile()) {
			gTxtExcel.setText(chooser.getSelectedFile().getAbsolutePath());
		}
	}// GEN-LAST:event_onBtnExcelMouseClicked

	/**
	 * 原始照片路径按钮被点击
	 * 
	 */
	private void onBtnSrcImageMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_onBtnSaveMouseClicked
		// TODO add your handling code here:
		JFileChooser chooser = new JFileChooser();
		chooser.setFileFilter(new DirectoriesFilter());
		chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		chooser.setAcceptAllFileFilterUsed(false);
		chooser.setDialogTitle("原始照片路径:");
		chooser.showOpenDialog(null);
		File file = chooser.getSelectedFile();
		if (file != null && file.exists()) {
			gTxtSrcImage.setText(chooser.getSelectedFile().getAbsolutePath());
		}
	}// GEN-LAST:event_onBtnSaveMouseClicked

	/**
	 * 合成按钮被点击
	 * 
	 */
	private void onBtnPieceMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_onBtnPieceMouseClicked
		// TODO add your handling code here:
		if (checkURL() == false) {
			return;
		}
		Global.startTime = new Date();
		Global.setEnable(false);
		Global.setState(Global.STATE_LOAD_EXCEL);
		if (excelParser == null) {
			excelParser = new ExcelParser();
		}
		excelParser.init();
		try {
			excelParser.readExcel(gTxtExcel.getText());
		} catch (Exception e) {
			// TODO Auto-generated catch block
			JOptionPane.showMessageDialog(null, "解析excel失败!");
			Global.setEnable(true);
			e.printStackTrace();
			return;
		}
		if (gRadioPiece.isSelected()) {
			ImageCreater.startThread();
			timer = new Timer();
			timer.schedule(new StateTimerTask(), 1000, 500);
		} else {
			ImageRenamer.startThread();
		}

	}// GEN-LAST:event_onBtnPieceMouseClicked

	/**
	 * 检测URL是否有问题
	 * 
	 */
	private boolean checkURL() {
		if (fileUtil.FileUtil.checkIsExcel(gTxtExcel.getText()) == false) {
			JOptionPane.showMessageDialog(null, "照片excel信息路径错误");
			return false;
		}
		if (FileUtil.checkIsDir(gTxtSrcImage.getText()) == false) {
			JOptionPane.showMessageDialog(null, "原始照片路径错误");
			return false;
		}
		if (FileUtil.checkIsDir(gTxtTarget.getText()) == false) {
			JOptionPane.showMessageDialog(null, "合成后存放图片目录错误");
			return false;
		}
		Global.srcImageURL = gTxtSrcImage.getText();
		Global.targetImageURL = gTxtTarget.getText();
		return true;
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PieceImage.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PieceImage.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PieceImage.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PieceImage.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				ViewProxy.pieceView.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton gBtnExcel;
	private javax.swing.JButton gBtnPiece;
	private javax.swing.JButton gBtnSrcImage;
	private javax.swing.JTextField gTxtExcel;
	private javax.swing.JTextField gTxtSrcImage;
	private javax.swing.JTextField gTxtState;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JProgressBar gStateBar;
	private final ButtonGroup menuGroup = new ButtonGroup();
	private JRadioButton gRadioPiece;
	private JPanel panel;
	private JLabel gLabelTarget;
	private JButton gBtnTarget;
	private JLabel gLabelW;
	private JTextField gTxtW;
	private JLabel gLabelWUnit;
	private JLabel gLabelH;
	private JTextField gTxtH;
	private JLabel gLabelHUnit;
	private JTextField gTxtTarget;
}
